<?php
declare(strict_types=1);date_default_timezone_set('Europe/London');header('Content-Type: application/json');header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
$db=new PDO('sqlite:/var/lib/clubdailyfive/player-wordle/game.sqlite3');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$action=$_GET['action']??'';$slug=preg_replace('/[^a-z0-9-]/','',$_GET['club']??'');$cq=$db->prepare("SELECT id FROM clubs WHERE slug=?");$cq->execute([$slug]);$cid=(int)$cq->fetchColumn();if(!$cid){http_response_code(404);echo'{}';exit;}
if($action==='suggest'){$term=trim($_GET['q']??'');$q=$db->prepare("SELECT id,name FROM players WHERE club_id=? AND name LIKE ? ORDER BY name LIMIT 8");$q->execute([$cid,'%'.$term.'%']);echo json_encode($q->fetchAll(PDO::FETCH_ASSOC));exit;}
if($action==='start'){$d=date('Y-m-d');$db->prepare("INSERT INTO aggregate_stats(stat_date,club_id,started) VALUES(?,?,1) ON CONFLICT(stat_date,club_id) DO UPDATE SET started=started+1")->execute([$d,$cid]);echo'{"ok":true}';exit;}
if($action==='guess'){
 $pid=(int)($_GET['player']??0);$d=date('Y-m-d');$q=$db->prepare("SELECT p.* FROM daily_game g JOIN players p ON p.id=g.player_id WHERE g.game_date=? AND g.club_id=?");$q->execute([$d,$cid]);$t=$q->fetch(PDO::FETCH_ASSOC);
 $q=$db->prepare("SELECT * FROM players WHERE id=? AND club_id=?");$q->execute([$pid,$cid]);$p=$q->fetch(PDO::FETCH_ASSOC);if(!$t||!$p){http_response_code(400);echo'{}';exit;}
 function mark($exact,$amber){return $exact?'green':($amber?'amber':'miss');}
 $m=['debut_age'=>mark($p['debut_age']==$t['debut_age'],abs($p['debut_age']-$t['debut_age'])<=2),'position'=>mark($p['position']==$t['position'],abs($p['position_rank']-$t['position_rank'])==1),
 'nationality'=>mark($p['nationality']==$t['nationality'],$p['continent']==$t['continent']),'debut_year'=>mark($p['debut_year']==$t['debut_year'],abs($p['debut_year']-$t['debut_year'])<=2),
 'prior_clubs'=>mark($p['prior_clubs']==$t['prior_clubs'],abs($p['prior_clubs']-$t['prior_clubs'])<=1)];
 echo json_encode(['correct'=>$p['id']==$t['id'],'name'=>$p['name'],'values'=>['debut_age'=>$p['debut_age'],'position'=>$p['position'],'nationality'=>$p['nationality'],'debut_year'=>$p['debut_year'],'prior_clubs'=>$p['prior_clubs']],'marks'=>$m]);exit;}
if($action==='answer'){$d=date('Y-m-d');$q=$db->prepare("SELECT p.name,p.debut_age,p.position,p.nationality,p.debut_year,p.prior_clubs FROM daily_game g JOIN players p ON p.id=g.player_id WHERE g.game_date=? AND g.club_id=?");$q->execute([$d,$cid]);$answer=$q->fetch(PDO::FETCH_ASSOC);if(!$answer){http_response_code(404);echo'{}';exit;}echo json_encode(['answer'=>$answer['name'],'values'=>['debut_age'=>$answer['debut_age'],'position'=>$answer['position'],'nationality'=>$answer['nationality'],'debut_year'=>$answer['debut_year'],'prior_clubs'=>$answer['prior_clubs']]]);exit;}
if($action==='finish'){$won=($_GET['won']??'0')==='1'?1:0;$guesses=max(1,min(5,(int)($_GET['guesses']??5)));$d=date('Y-m-d');$db->prepare("INSERT INTO aggregate_stats(stat_date,club_id,completed,won,guesses_total) VALUES(?,?,1,?,?) ON CONFLICT(stat_date,club_id) DO UPDATE SET completed=completed+1,won=won+excluded.won,guesses_total=guesses_total+excluded.guesses_total")->execute([$d,$cid,$won,$guesses]);$q=$db->prepare("SELECT p.name,p.debut_age,p.position,p.nationality,p.debut_year,p.prior_clubs FROM daily_game g JOIN players p ON p.id=g.player_id WHERE g.game_date=? AND g.club_id=?");$q->execute([$d,$cid]);$answer=$q->fetch(PDO::FETCH_ASSOC);echo json_encode(['answer'=>$answer['name'],'values'=>['debut_age'=>$answer['debut_age'],'position'=>$answer['position'],'nationality'=>$answer['nationality'],'debut_year'=>$answer['debut_year'],'prior_clubs'=>$answer['prior_clubs']]]);exit;}
echo'{}';