<?php
declare(strict_types=1); date_default_timezone_set('Europe/London'); header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
$db=new PDO('sqlite:/var/lib/predictioncomp/player-wordle/game.sqlite3');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$slug=preg_replace('/[^a-z0-9-]/','',$_GET['club']??'');$q=$db->prepare("SELECT id,name FROM clubs WHERE slug=? AND active=1");$q->execute([$slug]);$club=$q->fetch(PDO::FETCH_ASSOC);if(!$club){http_response_code(404);exit('Club not found');}$date=date('Y-m-d');
$g=$db->prepare("SELECT p.id FROM daily_game d JOIN players p ON p.id=d.player_id WHERE d.game_date=? AND d.club_id=?");$g->execute([$date,$club['id']]);$ready=(bool)$g->fetchColumn();$pcq=$db->prepare("SELECT COUNT(*) FROM players WHERE club_id=?");$pcq->execute([$club['id']]);$playerCount=(int)$pcq->fetchColumn();
function crest($s){$m=['man-city'=>'manchester-city','man-utd'=>'manchester-united','newcastle'=>'newcastle-united','tottenham'=>'tottenham-hotspur','leeds'=>'leeds-united','coventry'=>'coventry-city','hull'=>'hull-city','ipswich'=>'ipswich-town'];return $m[$s]??$s;}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=htmlspecialchars($club['name'])?> | Player Wordle</title><link rel="stylesheet" href="style.css?v=11"></head><body>
<header class="top"><a class="back" href="./">‹ CLUBS</a><a class="wordmark" href="./"><span class="crown">♛</span><b>PLAYER</b> <em>WORDLE</em><small>FOOTBALL KNOWS NO LIMITS</small></a><button class="info-button" type="button" aria-label="Player information" onclick="document.getElementById('player-info').showModal()">ⓘ <span>INFO</span></button></header>
<main class="game"><div class="game-club"><img src="../assets/crests/<?=htmlspecialchars(crest($slug))?>.png" alt=""><div><div class="eyebrow">TODAY'S CHALLENGE</div><h1><?=htmlspecialchars($club['name'])?></h1></div></div>
<?php if(!$ready):?><div class="notice">Today's mystery player is being prepared.</div><?php else:?><p class="attempts">Guess the mystery player — <b id="left">5</b> guesses remaining</p>
<div class="search"><input id="guess" autocomplete="off" placeholder="Type a player's name…"><div id="suggestions"></div></div><div class="board"><div class="labels"><span>DEBUT AGE<small>±2 close</small></span><span>POSITION<small>adjacent</small></span><span>NATIONALITY<small>continent</small></span><span>DEBUT YEAR<small>±2 close</small></span><span>PREV. CLUBS<small>±1 close</small></span></div><div id="rows"></div></div><div id="result"></div><button id="share" hidden>SHARE RESULT</button>
<script>window.GAME={club:<?=json_encode($slug)?>,name:<?=json_encode($club['name'])?>,date:<?=json_encode($date)?>};</script><script src="game.js?v=8"></script><?php endif?></main><dialog id="player-info" class="info-dialog"><form method="dialog"><button class="info-close" aria-label="Close">×</button><div class="eyebrow">PLAYER DATABASE</div><h2><?=htmlspecialchars($club['name'])?></h2><div class="club-player-total"><strong><?=number_format($playerCount)?></strong><span>players currently stored</span></div><div class="criteria"><h3>Who is included?</h3><p>A player must have made a competitive senior appearance for the club, have all five game attributes recorded, and meet at least one of the following four criteria:</p><ol><li>Played for the club this season or last season, regardless of which league the club played in.</li><li>Made at least 25 appearances for the club during the last 10 seasons.</li><li>Played for the club during the last 20 seasons and represented a European men’s national team.</li><li>Played in a cup-final victory for the club during the last 50 years.</li></ol><p class="info-note">The five stored clues are debut age, position, nationality, debut year and number of previous clubs.</p></div></form></dialog><footer>PAST • PRESENT • EVERY PLAYER HAS A STORY</footer></body></html>