<?php
declare(strict_types=1); date_default_timezone_set('Europe/London'); header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
$db=new PDO('sqlite:/var/lib/predictioncomp/player-wordle/game.sqlite3');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$clubs=$db->query("SELECT c.slug,c.name,COUNT(p.id) AS player_count FROM clubs c LEFT JOIN players p ON p.club_id=c.id WHERE c.active=1 GROUP BY c.id,c.slug,c.name ORDER BY c.name")->fetchAll(PDO::FETCH_ASSOC);
function crest($s){$map=['man-city'=>'manchester-city','man-utd'=>'manchester-united','newcastle'=>'newcastle-united','nottingham-forest'=>'nottingham-forest','tottenham'=>'tottenham-hotspur','aston-villa'=>'aston-villa','leeds'=>'leeds-united','coventry'=>'coventry-city','hull'=>'hull-city','ipswich'=>'ipswich-town'];return $map[$s]??$s;}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Player Wordle</title><link rel="stylesheet" href="style.css?v=11"></head><body>
<header class="top"><a class="wordmark" href="./"><span class="crown">♛</span><b>PLAYER</b> <em>WORDLE</em><small>FOOTBALL KNOWS NO LIMITS</small></a><button class="info-button" type="button" aria-label="Player information" onclick="document.getElementById('player-info').showModal()">ⓘ <span>INFO</span></button></header>
<main class="home"><section class="hero"><div class="eyebrow">DAILY PREMIER LEAGUE CHALLENGE</div><h1>Who is today's<br><span>mystery player?</span></h1><p>Choose a club. Five guesses. Five clues.</p></section>
<section class="club-panel"><div class="panel-title"><span>CHOOSE YOUR CLUB</span><i></i></div><div class="clubs">
<?php foreach($clubs as $c): $cr=crest($c['slug']);?><a class="club" href="game.php?club=<?=htmlspecialchars($c['slug'])?>" data-club="<?=htmlspecialchars($c['slug'])?>">
<img src="../assets/crests/<?=htmlspecialchars($cr)?>.png" alt="<?=htmlspecialchars($c['name'])?> crest"><strong><?=htmlspecialchars($c['name'])?></strong><small class="state"></small></a><?php endforeach?></div></section>
<div class="legend"><span><b class="lg green"></b>Exact</span><span><b class="lg amber"></b>Close</span><span><b class="lg grey"></b>Try again</span></div>
</main><dialog id="player-info" class="info-dialog"><form method="dialog"><button class="info-close" aria-label="Close">×</button><div class="eyebrow">PLAYER DATABASE</div><h2>Available players</h2><p class="info-intro">Current stored player totals for each club:</p><div class="player-counts"><?php foreach($clubs as $c):?><div><span><?=htmlspecialchars($c['name'])?></span><strong><?=number_format((int)$c['player_count'])?></strong></div><?php endforeach?></div><div class="criteria"><h3>Who is included?</h3><p>A player must have made a competitive senior appearance for the club, have all five game attributes recorded, and meet at least one of the following four criteria:</p><ol><li>Played for the club this season or last season, regardless of which league the club played in.</li><li>Made at least 25 appearances for the club during the last 10 seasons.</li><li>Played for the club during the last 20 seasons and represented a European men’s national team.</li><li>Played in a cup-final victory for the club during the last 50 years.</li></ol><p class="info-note">The five stored clues are debut age, position, nationality, debut year and number of previous clubs.</p></div></form></dialog><footer>PLAYER WORDLE <span>•</span> A NEW PLAYER EVERY DAY</footer>
<script>const today=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'});document.querySelectorAll('.club').forEach(x=>{let club=x.dataset.club,s={},g={};try{s=JSON.parse(localStorage.getItem('pw:'+club)||'{}');g=JSON.parse(localStorage.getItem('pwgame:'+today+':'+club)||'{}')}catch(e){}let state=x.querySelector('.state'),parts=[];if(s.streak>0)parts.push('🔥 '+s.streak+' streak');if(g.attempts>0&&!g.done)parts.push('IN PROGRESS');if(s.date===today&&s.done){x.classList.add('done');if(!parts.length)parts.push('PLAYED TODAY')}state.textContent=parts.join(' • ');});</script></body></html>